#
server:
  port: 9000
  servlet:
    context-path: /auth
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: auth-server
  thymeleaf:
    cache: false
    prefix: classpath:/templats
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template: true
