#
server:
  port: 9100
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: auth-server
  thymeleaf:
    cache: false
    prefix: classpath:/templats
    suffix: .jsp
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template: true
