#
server:
  port: 9100
  servlet:
    context-path: /clienta
#
logging:
  config: classpath:logback.xml

spring:
  application:
    name: sso-client-a
  thymeleaf:
    cache: false
    prefix: classpath:/templats
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template: true

####################
#（★）单点登录
####################
security:
  oauth2:
    client:
      client-id: client1
      client-secret: client1
      authorized-grant-types:
        - authorization_code
        - refresh_token
      scop: user_info
      user-authorization-uri: http://127.0.0.1:9000/auth/oauth/authorize
      access-token-uri: http://127.0.0.1:9000/auth/oauth/token
#      registered-redirect-uri:
#        - http://127.0.0.1:9200/client
#      use-current-uri: true
    resource:
      jwt:
        key-uri: http://127.0.0.1:9000/auth/oauth/token_key
        key-value: test
#      token-info-uri: htt://www.sohu.com
#    sso:
#      login-path: http://127.0.0.1:9100
