#
server:
  port: 9200
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: sso-client
  thymeleaf:
    cache: false
    prefix: classpath:/templats
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template: true

security:
  oauth2:
    client-id: client1
    client-secret: client1
    user-authorization-uri: http://127.0.0.1:9100/oauth/authorize
    access-token-uri: http://127.0.0.1:9100/oauth/token
    clientAuthenticationScheme: form
    scope: all
    sso:
      login-path: /login
  resource:
    jwt:
      key-uri: http://127.0.0.1:9100/oauth/token_key
