#
server:
  port: 9200
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: auth-server
  thymeleaf:
    cache: false
    prefix: classpath:/templats
    suffix: .jsp
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template: true

security:
  oauth2:
    client: clie
    clientSecret:
    user-authorization-uri:
    access-token-uri
